const audiosSonidosTarjeta = [
    ['ANITA-AR-EP-170923-0198.wav','','Anita','Las últimas respiraciones de tu vida','Anita hace una exploración vocal a partir de la instrucción: "Respira por un minuto como si fueran las últimas respiraciones de tu vida". Encuentro personal llevado a cabo en la residencia de Ale R y Anita el 17 de septiembre de 2023.','Santa Fe'],
    ['CELINA-CR-EP-281023-0324.wav','','Célina Fonseca Quirós','Que tu voz sea un medio para que el volcán se exprese','Celina Fonseca Quirós, después de recitar su poema "Acuarela con palabras", responde a la solicitud: "Que tu voz sea un medio para que el volcán se exprese". Grabación realizada en un encuentro personal en las faldas del volcán Turrialba el 28 de octubre de 2023.','Turrialba'],
    ['EMOVERE-CL-TG-221123-0427.wav','EMOVERE','Sebastián Chandía','Que tu voz exprese la memoria de tu gente más querida','Sebastián Chandía responde a la instrucción: "Que tu voz exprese la memoria de tu gente más querida". Grabación realizada dentro del taller "Lo que se pierde en la voz", llevado a cabo en la Facultad de Artes de la Universidad de Chile, con el grupo de danza Emovere, el 22 de noviembre de 2023.','Santiago'],
    ['EISNER-CL-EP-141223-0454.wav','','Federico Eisner','Regalo sonoro','Federico Eisner responde a la solicitud: "Envía con tu voz, sin usar palabras, un regalo sonoro a alguien a quien hayas amado profundamente y que ya no se encuentre contigo". Grabación realizada en un encuentro personal llevado a cabo en un departamento en la calle Santa Rosa, Santiago de Chile, el 14 de diciembre de 2023.','Santiago'],
    ['JAVERIANA-CO-TG-060324-0511.wav','Javeriana','Julieta Merizalde','Transmite con tu voz el sonido de tu historia','Julieta Merizalde responde a la solicitud: "Transmite con tu voz el sonido de tu historia". Grabación realizada en un taller que se llevó a cabo en la Facultad de Artes de la Pontificia Universidad Javeriana, en la asignatura "Materiales y técnicas de la música electrónica" del programa de estudios musicales, impartida por el profesor Julián Valdivieso, el 6 de marzo de 2024.','Bogotá'],
    ['UIS-CO-TG-130324-0566.wav','UIS','Ruth Johanna','Que la memoria de la censura se convierta en una firme expresión de libertad ','Ruth Johanna hace una improvisación vocal a partir de la instrucción: "Busca en tu memoria alguna voz que haya sido censurada en el pasado y se haya quedado atrapada en tu cuerpo. Recupera la voz censurada, abrázala, déjala crecer y utiliza tu voz actual para materializarla y dejar que finalmente resuene. Tómate el tiempo necesario para que la memoria de la censura se convierta en una firma expresión de libertad". Grabación realizada en el taller "Las memorias de la voz: las voces de la memoria", llevado a cabo en la Escuela de Artes y Música de la Universidad Industrial de Santander, en la ciudad de Bucaramanga, Colombia, el 11, 13 y 15 de marzo de 2024.','Bucaramanga'],
    ['PASCASIA-CO-TG-190324-0624.wav','La Pascasia','Jazzmincz','Cables de sonido','Jazzmincz hace una improvisación vocal a partir de la instrucción: "Expresa con tu voz un sonido que vincule tu ser, tu cuerpo y tus emociones con el entorno social en el que te encuentras en estos momentos. Imagina que de tus dedos, tu cabeza, tu boca y tu ombligo salen cables de sonido que se conectan con la historia y los afectos de cada una de las personas que te escuchan y acompañan en esta exploración". Grabación realizada en el taller "Resonancias espectrales de la voz", que se llevó a cabo en el centro cultural La Pascasia, en Medellín, Colombia, el 19 de marzo de 2024.','Medellín'],
    ['UNM-PE-TG-250424-0703.wav','UNM','Ingrid Lucía Antezana Soliz','Exploración de la voz como síntesis del ser','Ingrid Lucía Antezana Soliz hace una improvisación vocal a partir de la instrucción: "Emite con tu voz un sonido continuo, fuerte, profundo. Tómate el tiempo para sentir de qué manera ese sonido es resultado del vínculo entre tus entrañas, tu aparato fonador y todo tu cuerpo, y los afectos y memorias que conforman tu historia. Que el sonido de tu voz sea la síntesis de tu ser en todas las dimensiones de su espectro". Grabación realizada en el taller "Voces Espectrales", llevado a cabo en la Universidad Nacional de Música de Perú, en la ciudad de Lima, del 24 al 27 de abril de 2024.','Lima'],
    ['PUMPUMYACHKAN-PE-TG-160424-0651.wav','Pumpumyachkan','Santiago Malpartida (Ketamina)','Permite que tu voz te abrace y te acompañe','Santiago Malpartida (Ketamina) hace una improvisación vocal a partir de la instrucción: "Explora las regiones dolorosas de tu voz: tus duelos, tus heridas, esas partes de ti que normalmente intentas silenciar. Abraza con tu voz los sonidos que emites, sin juzgarlos ni reprimirlos. Permite que tu voz te abrace y te acompañe". Grabación realizada en el taller "Las historias de mi voz", en el marco del laboratorio de creación audiovisual "Pumpumyachkan 2024", que se llevó a cabo en la ciudad de Qosqo, Perú, del 16 al 18 de abril de 2024. ','Qosqo'],
    ['COYOACAN-MX-EP-180624-0741.wav','Coyoacán','Didanwy','Comparte con el mundo todas las emociones que vibras en tu cuerpo','Didanwy responde a la instrucción: "Dile al mundo lo que  sientes. Comparte con el mundo todas las emociones que vibran en tu cuerpo, sin emitir una sola palabra". Encuentro realizado en una residencia personal en Coyoacán, Ciudad de México, el 18 de junio de 2024. ','Coyoacán'],
];



const audiosPalabrasTarjeta = [
    ['MATAMAMI-AR-CA-290823-0036.wav','Matamami','Ana Laura Chimenti','Salvar a tu madre del dolor','Ana Laura Chimenti responde a la solicitud: "Busca en tu voz la sensación más antigua que tengas de haber querido salvar a tu madre del dolor". Grabación realizada para el proyecto Matamami, puesta en escena del actor y dramaturgo mexicano Marco Norzagaray a partir de la obra de la artista mexicana Amanda García.',''],
    ['UNR-AR-TG-180923-0201.wav','UNR','Paulina','Presentación y relación con la voz','Paulina se presentay habla de la relación que tiene con su voz. Grabación realizada dentro del taller "Los espectros de la voz: creación colectiva a partir de exploraciones de la voz propia", llevado a cabo en la Escuela de Música de la Universidad Nacional de Rosario (UNR) el 18 y 19 de septiembre de 2023.','Rosario'],
    ['UNTREF-AR-TG-270923-0237.wav','UNTREF','Geraldine A. Ruiz','Presentación y reflexión sobre la voz','Geraldine A. Ruiz se presenta y comparte una reflexión sobre el significado de la voz. Grabación realizada dentro del taller: "La voz de vos: a la escucha (mediada) de la voz propia", llevado a cabo en en la Maestría en arte estudios sonoros de la Universidad Nacional de Tres de Febrero (UNTREF), los días 27 y 28 de septiembre de 2023.','Buenos Aires'],
    ['UNTREF-AR-TG-270923-0241.wav','UNTREF','Nicolás Rey','Presentación y reflexión sobre la voz','Nicolás Rey se presenta y comparte una reflexión sobre el significado de la voz. Grabación realizada dentro del taller: "La voz de vos: a la escucha (mediada) de la voz propia", llevado a cabo en en la Maestría en arte estudios sonoros de la Universidad Nacional de Tres de Febrero (UNTREF), los días 27 y 28 de septiembre de 2023.','Buenos Aires'],
    ['TURRILIT-CR-TG-211023-0285.wav','Turrialba Literaria','Manolo','He tenido conflictos con mi voz','Manolo hace una exploración vocal a partir de la lectura de las reflexiones en verso tituladas "He tenido conflictos con mi voz". Grabación realizada en el taller "De la voz a la palabra", organizado en conjunto con el colectivo "Turrialba Literaria" en la Universidad de Costa Rica, sede del Atlántico, recinto Turrialba, con estudiantes de la univesidad e integrantes del mismo colectivo, el 21 de octubre de 2023.','Turrialba'],
    ['ALTOPACUARE-CR-TG-041123-0372.wav','Alto Pacuare','Naya(2)','Presentación y mensaje','Naya(2) se presenta y comparte un mensaje. Grabación realizada dentro de un taller que forma parte del trabajo colaborativo entre la artista indígena cabécar iLeana Obando del clan Tsirúrúwák y la compositora Susan Campos-Fonseca, quienes, junto a la Asociación de Mujeres Indígenas Kjala Bata de Alto Pacuare, desarrollan el Taller Bulalë (“sonoridades” en idioma Cabécar), con madres y niños(as) de la comunidad cabécar de Alto Pacuare, en la montañas de la Cuenca del Atlántico de Costa Rica.','Comunidad Alto Pacuare'],
    ['EMOVERE-CL-TG-221123-0414.wav','EMOVERE','Francisca Morand','Presentación y desapariciones de la voz','Francisca Morand se presenta y responde a la solicitud: "Háblanos de algún aspecto de tu voz que haya desaparecido". Grabación realizada dentro del taller "Lo que se pierde en la voz", llevado a cabo en la Facultad de Artes de la Universidad de Chile, con el grupo de danza Emovere, el 22 de noviembre de 2023.','Santiago'],
    ['IFG-CL-EP-291123-0478.wav','','Icha','Una historia usando el lenguaje de los cerros y las montañas','Icha responde a la solicitud: "Cuéntanos una historia usando el lenguaje de los cerros y las montañas". Grabación realizada en un encuentro personal con Icha, Aida Francisca, Gabriel y Carlos Alberto Hernández Navarrete en la ciudad de Valparaíso, Chile, el 29 de diciembre de 2023.','Valparaíso'],
    ['JAVERIANA-CO-TG-060324-0494.wav','Javeriana','Andrés Guzmán','Presentación y escucha de la voz','Andrés Guzmán se presenta y responde a la pregunta: "¿Qué escucho cuando escucho la voz?" Grabación realizada en un taller que se llevó a cabo en la Facultad de Artes de la Pontificia Universidad Javeriana, en la asignatura "Materiales y técnicas de la música electrónica" del programa de estudios musicales, impartida por el profesor Julián Valdivieso, el 6 de marzo de 2024.','Bogotá'],
    ['PUMPUMYACHKAN-PE-TG-160424-0645.wav','Pumpumyachkan','AmapoXio','Historia de mi voz','Delfina Nina relata la historia de su voz. Grabación realizada en el taller "Las historias de mi voz", en el marco del laboratorio de creación audiovisual "Pumpumyachkan 2024", que se llevó a cabo en la ciudad de Qosqo, Perú, del 16 al 18 de abril de 2024. ','Qosqo'],
];